### **№4**

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import random
from scipy import stats

Строим выборку размера n = 100 равномерного распределения U(θ, 2θ), при θ = 10

In [79]:
n = 100
θ = 10
sample = stats.uniform.rvs(size=n)*θ + θ
sample

array([13.96241304, 16.73451854, 18.58522738, 18.65448528, 17.78607356,
       15.97271905, 13.01528872, 16.68633512, 13.1035419 , 11.25193744,
       11.98566392, 14.5955065 , 16.0182553 , 15.64452551, 14.76799974,
       12.84915103, 16.56853173, 18.50671569, 11.80950377, 11.46713266,
       11.40779212, 14.26755575, 18.54523674, 11.5101879 , 15.18163214,
       10.33659956, 10.26404807, 17.2166167 , 17.77960508, 19.12213868,
       15.86449512, 13.8794165 , 12.40220321, 16.8350443 , 11.83513713,
       16.94192575, 15.82633901, 19.46611245, 19.26225004, 13.32998395,
       18.28398968, 13.88019751, 13.52633626, 11.85320633, 18.86715726,
       14.26827203, 19.08321578, 10.09313715, 18.99783953, 14.4792087 ,
       15.01906483, 15.68269574, 12.92609426, 13.62231524, 13.9797267 ,
       14.95339633, 11.80663176, 14.7673457 , 10.61685028, 14.90381025,
       16.55794023, 15.97786293, 14.24158968, 17.73825194, 10.40144252,
       14.94033183, 15.33421968, 10.30800448, 10.64695635, 15.64

Оценки параметра θ

In [80]:
xmax = sample.max() #x(n) - максимум выборки 
xmin = sample.min() #x(1) - минимум выборки 
𝛼1 = np.mean(sample) #оценка первого момента
θ1 = 2/3*𝛼1 #оценка методом моментов
θ2 = (n+1)/(2*n+1)*xmax #несмещенная оценка методом правдоподобия
θ3 = (n+1)/(5*n+4)*(xmin + 2*xmax) #предложенная оценка
print("оценка методом моментов: {:.3f}".format(θ1))
print("несмещенная оценка методом правдоподобия: {:.3f}".format(θ2))
print("предложенная оценка: {:.3f}".format(θ3))

оценка методом моментов: 9.779
несмещенная оценка методом правдоподобия: 9.878
предложенная оценка: 9.893


Строим точный и ассимптотический доверительные интервалы для параметра θ

In [81]:
β = 0.95 #доверительная вероятность
𝛼2 = 0 #несмещенная оценка второго момента
for xi in sample:
  𝛼2 += xi*xi/(n-1)
print("[{:.3f}, {:.3f}] - точный".format(xmax/(((1+β)/2)**(1/n)+1), xmax/(((1-β)/2)**(1/n)+1)))
print("[{:.3f}, {:.3f}] - ассимптотический".format((-1.96)*2/3*((𝛼2-𝛼1*𝛼1)**(1/2)) + 2/3*𝛼1, (1.96)*2/3*((𝛼2-𝛼1*𝛼1)**(1/2)) + 2/3*𝛼1))

[9.830, 10.010] - точный
[5.522, 14.036] - ассимптотический


Параметрический бутстраповский доверительный интервал

In [82]:
N = 1000
subsamples = np.zeros((N, n))
Δ1 = np.zeros(N)
Δ2 = np.zeros(N)
for i in range(N):
    subsamples[i] = np.random.choice(sample, size = n)  #составляем подвыборки
    Δ1[i] = 2/3*np.mean(subsamples[i]) - θ1
    Δ2[i] = (n+1)/(2*n+1)*subsamples[i].max() - θ2
Δ1.sort() #вариационные ряды
Δ2.sort()
print("[{:.3f}, {:.3f}] - ОММ".format(θ1 - Δ1[974], θ1 - Δ1[24]))
print("[{:.3f}, {:.3f}] - ОМП".format(θ2 - Δ2[974], θ2 - Δ2[24]))

[9.399, 10.136] - ОММ
[9.878, 10.081] - ОМП


Непараметрический бутстраповский доверительный интервал для двух оценок: θ1 = 9.779 и θ2 = 9.878

In [84]:
N = 50000
θ1_ = np.zeros(N)
θ2_ = np.zeros(N)
for i in range(N):
    subsample1 = stats.uniform.rvs(size=n)*θ1 + θ1 #составляем подвыборки для θ1 - ОММ
    subsample2 = stats.uniform.rvs(size=n)*θ2 + θ2 #составляем подвыборки для θ2 - ОМП
    θ1_[i] = 2/3*np.mean(subsample1) 
    θ2_[i] = (n+1)/(2*n+1)*subsample2.max()
θ1_.sort() #вариационные ряды
θ2_.sort()
print("[{:.3f}, {:.3f}] - ОММ".format(θ1_[24], θ1_[974]))
print("[{:.3f}, {:.3f}] - ОМП".format(θ2_[24], θ2_[974]))

[9.158, 9.385] - ОММ
[9.569, 9.736] - ОМП
